### ISSUE TITLE
Couldn't run the example

### ISSUE THREAD

**Issue by asayici** [ikmb/eagleimp#3]
Hi, 
I hardly managed to install the eagleimp and finally tried to run example you provided. However I got some errors: 

##########
----------------------------------------------------------------
--- Chunk 1/1:
----------------------------------------------------------------
Reading data: 0%[E::_reader_seek] Could not seek: 22:1--2
eagleimp: synced_bcf_reader.c:448: _reader_seek: Assertion `0' failed.
Aborted (core dumped)
##########

Do you think the error is related with me or something is wrong?

**Comment by lwienbrandt** [comment]
Dear asayici,
thanks for using EagleImp.
Your problem is related to htslib. 
So, what OS and what version of htslib do you use? For me on Ubuntu 22.04 with htslib 1.15.1 the example works fine.
But you gave me a hint. I realized that a new version of htslib was launched this summer (1.16). Probably, this causes an error and I will have to fix that... Will check that.

**Comment by asayici** [comment]
Hi lwienbrandt,
I am using centOS 7.9. I tried to use htslib 1.15.1 as you specified and the problem is still continue.

**Comment by lwienbrandt** [comment]
Dear asayici,
I'm sorry, I'm still not able to reproduce your error. Even htslib 1.16 works fine for me.
However, please ensure that you built and linked the project against the correct version of htslib (not a version which was probably installed beforehand by your OS).
I'm pointing this out because the error message you stated seems to originate from the file synced_bcf_reader.c in line 448. However, neither in version 1.15.1 nor in version 1.16 of htslib the assertion that failed is located in line 448, it is in line 532.
So, my bet is that you linked against another htslib version.
If you installed htslib according to the instructions on Github, you should end up with an installation somewhere similar to /usr/local/lib. If you run cmake to build EagleImp, can you confirm that it finds the correct location?

**Comment by asayici** [comment]
Yess, you are right. The system has htslib 1.5 and interestingly one of the lib files is coming from that version. I simply added a path line in the FindHTSlib.cmake file and the problem is solved. Thank you for your help. 

Bests
